require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ArtefactsController do
  render_views
  

  describe "GET index" do
    
  end
  
  describe "access control" do

    it "should deny access to 'create'" do
      post :create
      response.should redirect_to(login_path)
    end

    it "should deny access to 'destroy'" do
      delete :destroy, :id => 1
      response.should redirect_to(login_path)
    end
  end
  
  describe "POST 'create'" do

      before(:each) do
        @user = test_sign_in(Factory(:user))
      end

      describe "failure" do

        before(:each) do
          @attr = { :name => "", :description => "Example artefact" }
        end

        it "should not create an artefact" do
          lambda do
            post :create, :artefact => @attr
          end.should_not change(artefact, :count)
        end

        pending "should render the home page" do
          post :create, :artefact => @attr
          response.should render_template('pages/home')
        end
      end

      describe "success" do

        before(:each) do
          @attr = { :name => "Artefact", :description => "Example artefact" }
        end

        it "should create a artefact" do
          lambda do
            post :create, :artefact => @attr
          end.should change(artefact, :count).by(1)
        end

        pending "should redirect to the home page" do
          post :create, :artefact => @attr
          response.should redirect_to(root_path)
        end

        it "should have a flash message" do
          post :create, :artefact => @attr
          flash[:success].should =~ /successfully/i
        end
      end
    end
    
    describe "DELETE 'destroy'" do
        describe "for an unauthorized user" do

          before(:each) do
            @user = Factory(:user)
            wrong_user = Factory(:user, :email => Factory.next(:email))
            test_sign_in(wrong_user)
            @artefact = Factory(:artefact, :user => @user)
          end

          it "should deny access" do
            delete :destroy, :id => @artefact
            response.should redirect_to(root_path)
          end
        end

        describe "for an authorized user" do
          
          before(:each) do
            @user = test_sign_in(Factory(:user))
            @artefact = Factory(:artefact, :user => @user)
          end

          it "should destroy the micropost" do
            lambda doartefact
              delete :destroy, :id => @micropost
            end.should change(Artefact, :count).by(-1)
          end
        end
      end

end
